name: Build GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run build script
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./scripts/buildpages.sh
          git add -A
          git commit -m 'build pages'
          git push --set-upstream origin pages
